kind: AIchorManifest
apiVersion: 0.2.2

builder:
  image: image
  dockerfile: ./dockerfiles/ray.Dockerfile
  context: .

spec:
  operator: kuberay
  image: image
  command: "python3 -u main.py --operator=kuberay --sleep=3000 --tb-write=True"
 
  debug:
    jupyter: false

  tensorboard: 
    enabled: true
  securityContext:
      ptrace: true
 
  types: 
    Head:
      rayStartParams: # optional, can be empty
        ray-debugger-external: "true"
        object-store-memory: "3000000000"
      resources:
        cpus: 5
        ramRatio: 2

    Workers:
      - name: cpu-workers
        count: 1
        rayStartParams: # optional, can be empty
          ray-debugger-external: "true"
          object-store-memory: "1000000000"
        resources: 
          cpus: 5
          ramRatio: 2
          shmSizeGB: 0
          accelerators: # optional
            gpu:
              count: 1
              type: gpu
              product: nvidia-tesla-t4 



          
