kind: AIchorManifest 
apiVersion: 0.2.2

builder:
  image: image 
  dockerfile: ./dockerfiles/Dockerfile
  context: .

spec:
  operator: tf
  image: image
  command: "cat value.txt && echo $KEY_RUN && python3 -u maine.py --operator=tf --sleep=300 --tb-write=True"

  tensorboard:
    enabled: true

  types:
    Worker:
      count: 1
      resources:
        cpus: 1
        ramRatio: 2
        shmSizeGB: 0
        accelerators: # optional
          gpu:
            count: 0
            type: gpu
            product: nvidia-tesla-t4
