kind: AIchorManifest
apiVersion: 0.2.2

builder:
  image: image
  dockerfile: ./dockerfiles/ray.Dockerfile
  context: .

spec:
  operator: kuberay
  image: image
  command: "python3 -u main.py --operator=kuberay --sleep=30 --tb-write=True"
 
  debug:
    jupyter: false

  tensorboard: 
    enabled: true
  securityContext:
      ptrace: true
 
  types: 
    Head:
      resources:
        cpus: 5
        ramRatio: 2

    Workers:
      - name: cpu-workers
        count: 50
        resources: 
          cpus: 1
          ramRatio: 2
          shmSizeGB: 0
          accelerators: # optional
            gpu:
              count: 0
              type: gpu
              product: nvidia-tesla-t4 



          
